from django.conf.urls import patterns, url
from AdminUnit import views

urlpatterns = patterns('',
                       url(r'^$', views.index),
                       url(r'^register/$', views.register),
                       url(r'^event/$', views.editEvent),
                       url(r'^event/(?P<eventId>\d+)/$', views.editEvent),
                       url(r'^deleteEvent/(?P<eventId>\d+)/$', views.deleteEvent),
                       url(r'^allEvents/$', views.allEvents),
                       url(r'^job/$', views.job),
                       url(r'^job/(?P<jobId>\d+)/$', views.job),
                       url(r'^allJobs/$', views.allJobs),
                       url(r'^deleteJob/(?P<jobId>\d+)/$', views.deleteJob),
                       url(r'^org/$', views.editOrg),
                       url(r'^org/(?P<orgId>\d+)/$', views.editOrg),
                       url(r'^deleteOrg/(?P<orgId>\d+)/$', views.deleteOrg),
                       url(r'^allOrgs/$', views.allOrgs),
                       url(r'^login/$', views.login_process),
                       url(r'^logout/$', views.logout_process),
                       url(r'^searchByEvent/$', views.searchByEvent),
                       url(r'^searchByOrg/$', views.searchEmployeeByOrg),
                       url(r'^searchByTime/$', views.searchByTime),
                       url(r'^shift/$', views.manageShift),
                       url(r'^shift/(?P<shiftId>\d+)/$', views.manageShift),
                       url(r'^deleteShift/(?P<shiftId>\d+)/$', views.deleteShift),
                       url(r'^allShifts/$', views.allShifts),
                       url(r'^createShift/(?P<jobId>\d+)/(?P<eventId>\d+)/(?P<userName>\w+)/$', views.createShift),
                       url(r'^reportHoursByOrg/$', views.reportHoursByOrg),
                       url(r'^reportHoursByEvent/$', views.reportHoursByEvent),
                       url(r'^reportHoursByTime/$', views.reportHoursByTime),
                       url(r'^reportVolunteersByOrg/$', views.reportVolunteersByOrg),
                       url(r'^reporting/$', views.reportHoursByTimeAndOrg),
                       )
