language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE DATABASE vms;" -U postgres
script:
  - cd vms
  - coverage run --source='.' manage.py test
after_success:
    coveralls
